### PR TITLE
Remove PREFIX functionality

### PR DESCRIPTION
**Pull request by mfurseman**
It's no longer required as at this stage of the conversions we are no longer using CONVERTER_ROOT.

### CODE REVIEW

**Comment by mfurseman** [comment]
@nickbattam @willrogers

**Comment by nickbattam** [comment]
This feature is still helpful when running conversions

**Comment by willrogers** [comment]
Oops.

I haven't used it for a while.

**Comment by nickbattam** [comment]
No need to revert; it is noise in all the released modules and simple enough to work around.

**Pull request merged**
